---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  namespace: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2024-02-08 - 12:48:42 +0000
  labels:
    app: quarkus-inventory
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: inventory-service
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inventory-service-view
  namespace: demo
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: inventory-service
    namespace: demo
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2024-02-08 - 12:48:42 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /inventory/q/metrics
    prometheus.io/port: "8091"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app: quarkus-inventory
    app.kubernetes.io/managed-by: quarkus
  name: inventory-service
  namespace: demo
spec:
  ports:
    - name: http
      port: 8091
      protocol: TCP
      targetPort: 8091
  selector:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2024-02-08 - 12:48:42 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /inventory/q/metrics
    prometheus.io/port: "8091"
    prometheus.io/scheme: http
  labels:
    app: quarkus-inventory
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: inventory-service
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-service
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2024-02-08 - 12:48:42 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /inventory/q/metrics
        prometheus.io/port: "8091"
        prometheus.io/scheme: http
      labels:
        app: quarkus-inventory
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: inventory-service
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
      namespace: demo
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quarkus/quarkus-inventory-service-jvm:v1
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /inventory/q/health/live
              port: 8091
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: inventory-service
          ports:
            - containerPort: 8091
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /inventory/q/health/ready
              port: 8091
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 45
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /inventory/q/health/started
              port: 8091
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: inventory-service
